DATASET: 'pycfg.base.opv2v.seq1_vox04'


CONTROLLER:
  num_loss_frame: 1
  data_manager: 'pycfg.base.opv2v.data_manager'
  shared_modules: {}
  cav_manager:
    prototype: sparse_align_collection.slcOPV2V
    memory_len: 1

VISUALIZATION:
  output_viewer:
    plots: []




